### ISSUE TITLE
TST: Add tests

### ISSUE THREAD

**Issue by pllim** [spacetelescope/wiimatch#6]
I don't see any tests.

**Comment by mcara** [comment]
Because there aren't any. Tests are coming soon...

**Comment by mcara** [comment]
@pllim See #7

Also, @jhunkeler please add the rest of the machinery

**Comment by mcara** [comment]
Hm, locally, coverage was ~75%. @jhunkeler knows some extreme settings => I'll add some more coverage later.

**Comment by mcara** [comment]
Tests have been added in https://github.com/spacetelescope/wiimatch/pull/7
